name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        working-directory: ./issues-reader
        run: go build

      - name: Generate token for Camunda GitHub org
        id: generate-camunda-github-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          repository: marcosgvieira/agile

      - name: Run release notes script
        working-directory: ./issues-reader
        run: set -o pipefail; ./issues-reader | tee release_notes.txt
        env:
          GITHUB_CAMUNDA_ACCESS_TOKEN: ${{ steps.generate-camunda-github-token.outputs.token }}