name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve commits for release
        id: commits
        run: |
          git fetch --depth=1 origin +refs/tags/$(git describe --abbrev=0 222^):
          echo "::set-output name=commits::$(git log --pretty=format:'%h' --abbrev-commit ${previous_tag}..${{ github.event.release.tag_name }})"

      - name: Get correlated issues
        id: issues
        uses: gavinr/github-issues-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commits: ${{ steps.commits.outputs.commits }}

      - name: Search for SEC-123
        id: search
        run: |
          commits=$(echo "${{ steps.commits.outputs.commits }}" | sed 's/ /\\|/g')
          pattern="SEC-123"
          matches=$(echo "${{ steps.issues.outputs.issue_list }}" | grep -E "($commits).*($pattern)")
          
          if [[ -n "$matches" ]]; then
            echo "::set-output name=found::true"
          else
            echo "::set-output name=found::false"
          fi

      - name: Send Slack message
        if: steps.search.outputs.found == 'true'
        uses: rtCamp/action-slack-notify@v3
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          channel: '#general'
          message: 'SEC-123 found in release commits!'

